DROP TABLE IF EXISTS reservations_list_commodations;
DROP TABLE IF EXISTS reservations_list;
DROP TABLE IF EXISTS commodation;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS host;
DROP TABLE IF EXISTS country;

create table country
(
    id bigint generated by default as identity primary key,
    name varchar(200),
    continent varchar(200)
);

create table host
(
    id bigint generated by default as identity primary key,
    name varchar(200),
    surname varchar(200),
    country_id bigint references country
);

create table commodation
(
    id bigint generated by default as identity primary key,
    name varchar(200),
    category varchar(200),
    host_id bigint references host,
    num_Rooms integer,
    reserved boolean default false
);

create table users
(
    username varchar(255) primary key,
    password varchar(255),
    name varchar(255),
    surname varchar(255),
    isAccountNonExpired boolean default true,
    isAccountNonLocked boolean default true,
    isCredentialsNonExpired boolean default true,
    isEnabled boolean default true,
    role varchar(50)
);

CREATE TABLE reservations_list
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) UNIQUE REFERENCES users(username)
);

CREATE TABLE reservations_list_commodations
(
   reservations_list_id bigint REFERENCES reservations_list(id) ON DELETE CASCADE,
   commodations_id bigint REFERENCES commodation(id) ON DELETE CASCADE,
   PRIMARY KEY (reservations_list_id, commodations_id)
);